const enStrings = {
  "unknownError": "Unknown error",
  "notice": "Notice",
  "close": "Close",
  "continues": "Continue",
  "setting": "Setting",
  "cancel": "Cancel",
  "noNetTitle": "No internet connection",
  "noNetContent": "No internet connection, please try again later",
  "retry": "Retry",
  "allow": "Allow",
  "removeAds": "Remove Ads",
  "privacy": "Privacy",
  "termOfCondition": "Term of Condition",
  "contactUs": "Contact us",
  "shareApp": "Share app",
  "language": "Language",
  "restore": "Restore",
  "moreApp": "More app",
  "errorLoadAds": "The function is not ready, please try again in a moment",
  "shareMessage":
      "Install to update outside temperature, humidity, weekly weather forecast and AQI to protect yourself and your family",
  "bloodHealth": "Blood Health",
  "heartRate": "Heart Rate",
  "bloodPressure": "Blood Pressure",
  "bloodSugar": "Blood Sugar",
  "weightAndBMI": "Weight & BMI",
  "foodScanner": "Food Scanner",
  "home": "Home",
  "insights": "Insights",
  "alarm": "Alarm",
};
