const enStrings = {
  "unknownError": "Unknown error",
  "notice": "Notice",
  "close": "Close",
  "continues": "Continue",
  "setting": "Setting",
  "cancel": "Cancel",
  "noNetTitle": "No internet connection",
  "noNetContent": "No internet connection, please try again later",
  "retry": "Retry",
  "allow": "Allow",
  "removeAds": "Remove Ads",
  "privacy": "Privacy",
  "termOfCondition": "Term of Condition",
  "contactUs": "Contact us",
  "shareApp": "Share app",
  "language": "Language",
  "restore": "Restore",
  "moreApp": "More app",
  "errorLoadAds": "The function is not ready, please try again in a moment",
  "shareMessage":
      "Install to update outside temperature, humidity, weekly weather forecast and AQI to protect yourself and your family",
  "bloodHealth": "Blood Health",
  "heartRate": "Heart Rate",
  "bloodPressure": "Blood Pressure",
  "bloodSugar": "Blood Sugar",
  "weightAndBMI": "Weight & BMI",
  "foodScanner": "Food Scanner",
  "home": "Home",
  "insights": "Insights",
  "alarm": "Alarm",
  "export": "Export",
  "average": "Average",
  "min": "Min",
  "max": "Max",
  "measureNow": "Measure Now",
  "setAlarm": "Set Alarm",
  "addData": "Add Data",
  "stop": "Stop",
  "add": "Add",
  "measuring": "Measuring",
  "placeYourFinger": "Place your finger on camera",
  "measureNowOrAdd": "Measure now or add your record to see statistics",
  "measure": "Measure",
  "permissionCameraDenied01": "Please allow the app to access the device's camera to measure heart rate",
  "permissionCameraSetting01":
      "Please go to settings and allow the app to access your device's camera to measure heart rate",
  "permissionCameraDenied02": "Please allow the app to access your device's camera to scan the code",
  "permissionCameraSetting02":
      "Please go to the settings and allow the app to access the device's camera to scan the code",
  "restingHeartRate": "Resting Heart Rate",
  "slow": "Slow",
  "normal": "Normal",
  "fast": "Fast",
  "age": "Age",
  "choseYourAge": "Chose your age",
  "choseYourGender": "Chose your gender",
  "save": "Save",
  "rhSlowMessage": "Cautious! Your heart rate is too low",
  "rhNormalMessage": "Great! Your heart rate remains in the normal range",
  "rhFastMessage": "Cautious! Your heart rate is higher than normal",
};
