const viStrings = {
  "unknownError": "Lỗi không xác định",
  "notice": "Thông báo",
  "close": "Đóng",
  "continues": "Tiếp tục",
  "setting": "Cài đặt",
  "cancel": "Huỷ",
  "noNetTitle": "Không có kết nối mạng",
  "noNetContent": "Không có kết nối mạng, vui lòng thử lại sau",
  "retry": "Thử lại",
  "allow": "Cho phép",
  "removeAds": "Loại bỏ quảng cáo",
  "privacy": "Quyền riêng tư",
  "termOfCondition": "Điều khoản sử dụng",
  "contactUs": "Liên hệ",
  "shareApp": "Chia sẻ",
  "language": "Ngôn ngữ",
  "restore": "Khôi phục",
  "moreApp": "Các ứng dụng khác",
  "errorLoadAds": "Chức năng chưa sẵn sàng, vui lòng thử lại sau giây lát",
  "shareMessage":
      "Tải app để theo dõi nhiệt độ ngoài trời, độ ẩm, cập nhật tình hình thời tiết và chỉ số ô nhiễm không khí để bảo vệ bản thân và gia đình bạn",
  "bloodHealth": "Blood Health",
  "heartRate": "Nhịp tim",
  "bloodPressure": "Huyết áp",
  "bloodSugar": "Đường huyết",
  "weightAndBMI": "Cân nặng & BMI",
  "foodScanner": "Quét thực phẩm",
  "home": "Trang chủ",
  "insights": "Chi tiết",
  "alarm": "Đặt giờ",
  "export": "Xuất",
  "average": "Trung bình",
  "min": "Nhỏ nhất",
  "max": "Lớn nhất",
  "measureNow": "Đo Ngay",
  "setAlarm": "Đặt Nhắc nhở",
  "addData": "Thêm Dữ Liệu",
  "stop": "Dùng",
  "add": "Thêm",
  "measuring": "Đang đo",
  "placeYourFinger": "Đặt ngón tay của bạn trên máy ảnh",
  "measureNowOrAdd": "Đo ngay bây giờ hoặc thêm hồ sơ của bạn để xem số liệu thống kê",
  "measure": "Đo",
  "permissionCameraDenied01": "Vui lòng cho phép ứng dụng truy cập camera của thiết bị để đo nhịp tim",
  "permissionCameraSetting01":
      "Vui lòng vào phần cài đặt và cho phép ứng dụng truy cập camera của thiết bị để đo nhịp tim",
  "permissionCameraDenied02": "Vui lòng cho phép ứng dụng truy cập camera của thiết bị để tiến hành quét mã",
  "permissionCameraSetting02":
      "Vui lòng vào phần cài đặt và cho phép ứng dụng truy cập camera của thiết bị để tiến hành quét mã",
  "restingHeartRate": "Nhịp tim nghỉ ngơi",
  "slow": "Chậm",
  "normal": "Bình thường",
  "fast": "Nhanh",
  "age": "Tuổi",
  "choseYourAge": "Chọn tuổi của bạn",
  "choseYourGender": "Chọn giới tính của bạn",
  "save": "Lưu",
  "rhSlowMessage": "Chú ý! Nhịp tim của bạn quá thấp",
  "rhNormalMessage": "Tuyệt! Nhịp tim của bạn vẫn ở mức bình thường",
  "rhFastMessage": "Chú ý! Nhịp tim của bạn cao hơn bình thường",
  "addSuccess": "Thêm dữ liệu thành công",
  "date": "Ngày",
  "time": "Giờ",
  "gender": "Giới tính",
  "delete": "Xoá",
  "deleteData": "Xoá dữ liệu",
  "deleteDataConfirm": "Bạn muốn xoá dữ liệu này?",
};
