const viStrings = {
  "unknownError": "Lỗi không xác định",
  "notice": "Thông báo",
  "close": "Đóng",
  "continues": "Tiếp tục",
  "setting": "Cài đặt",
  "cancel": "Huỷ",
  "noNetTitle": "Không có kết nối mạng",
  "noNetContent": "Không có kết nối mạng, vui lòng thử lại sau",
  "retry": "Thử lại",
  "allow": "Cho phép",
  "removeAds": "Loại bỏ quảng cáo",
  "privacy": "Quyền riêng tư",
  "termOfCondition": "Điều khoản sử dụng",
  "contactUs": "Liên hệ",
  "shareApp": "Chia sẻ",
  "language": "Ngôn ngữ",
  "restore": "Khôi phục",
  "moreApp": "Các ứng dụng khác",
  "errorLoadAds": "Chức năng chưa sẵn sàng, vui lòng thử lại sau giây lát",
  "shareMessage":
      "Tải app để theo dõi nhiệt độ ngoài trời, độ ẩm, cập nhật tình hình thời tiết và chỉ số ô nhiễm không khí để bảo vệ bản thân và gia đình bạn",
  "bloodHealth": "Blood Health",
  "heartRate": "Nhịp tim",
  "bloodPressure": "Huyết áp",
  "bloodSugar": "Đường huyết",
  "weightAndBMI": "Cân nặng & BMI",
  "foodScanner": "Quét thực phẩm",
  "home": "Trang chủ",
  "insights": "Chi tiết",
  "alarm": "Đặt giờ",
};
